name: termulscan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ─── UTILITY ────────────────────────────────────────────────
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.3.1
  device_info_plus: ^9.1.0
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  collection: ^1.18.0
  archive: ^3.6.1
  file_picker: ^8.0.0

  # ─── SCANNER & MEDIA ──────────────────────────────────────
  mobile_scanner: ^5.2.0
  saver_gallery: ^3.0.0
  share_plus: ^10.1.4
  image: ^4.1.7
  camera: ^0.10.5+5
  video_player: ^2.8.5
  video_thumbnail: ^0.5.6

  # ─── GPS / LOKASI ───────────────────────────────────────────
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.2.2
  rxdart: ^0.28.0

  # ─── DATABASE ──────────────────────────────────────────────
  sqflite: ^2.3.0
  path: ^1.9.0

  # ─── FFMPEG (STABIL) ──────────────────────────────────────
  ffmpeg_kit_flutter_new: ^4.1.0

  # ─── STATE MANAGEMENT ──────────────────────────────────────
  provider: ^6.0.5   # ✅ TAMBAHKAN INI

  # ─── BACKGROUND & NOTIFICATIONS ──────────────────────────
  flutter_foreground_task: ^9.2.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
