name: termulscan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'                    # ✅ SDK constraint yang diminta

dependencies:
  flutter:
    sdk: flutter

  # Core
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.3.3

  # UI
  gap: ^3.0.1
  flutter_animate: ^4.5.0

  # Scanner
  mobile_scanner: ^5.2.0

  # Gallery
  saver_gallery: ^3.0.0

  # Share
  share_plus: ^9.0.0

  # SVG (jika perlu)
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
